### ISSUE TITLE
404 error for loader.gif 

### ISSUE THREAD

**Issue by oeway** [MouseLand/cellpose_web#3]
Hi, could you please check if you have [this file](https://github.com/MouseLand/cellpose_web/blob/main/static/images/loader.gif) correctly served from the server?

I am getting the following error:
```
(index):191 GET https://www.cellpose.org/static/images/loader.gif 404 (NOT FOUND)
```
Thanks.

**Comment by carsen-stringer** [comment]
oops just added this

**Comment by oeway** [comment]
It works, thanks!
